AplikacijaDijeljenihRadnihMjesta/Models/ViewModel/OdobravanjeZahtjeva.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AplikacijaDijeljenihRadnihMjesta.Models.ViewModel
{
    public class OdobravanjeZahtjeva
    {
        public int Id
        {
            get; set;
        }

        public List<RezervacijeOtkazivanjeVM> RezervacijeOtkazivanje
        {
            get; set;
        }

        public List<string> DjelatnikEmail
        {
            get; set;
        }
        public int? Status
        {
            get; set;
        }
        
        public List<SelectListItem> Statusi
        {
            get; set;
        }

        public string povratnaInfo { get; set; }

    }
}

AplikacijaDijeljenihRadnihMjesta/Controllers/OdobravanjeZahtjevaController.cs
using AplikacijaDijeljenihRadnihMjesta.Data;
using AplikacijaDijeljenihRadnihMjesta.Models;
using AplikacijaDijeljenihRadnihMjesta.Models.Paginacija;
using AplikacijaDijeljenihRadnihMjesta.Models.ViewModel;
using AplikacijaDijeljenihRadnihMjesta.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AplikacijaDijeljenihRadnihMjesta.Controllers
{
    public class OdobravanjeZahtjevaController : Controller
    {

        private OdobravanjeZahtjevaRepository odobravanjeZahtjevaRepository;
        private MailRequest request = new MailRequest();
        private readonly IMailService mailServices;
        const string SessionStatus = "_Statusi";
        public OdobravanjeZahtjevaController(AppDbContext db, IMailService mailServices)
        {
            this.odobravanjeZahtjevaRepository = new OdobravanjeZahtjevaRepository(db, mailServices);
            this.mailServices = mailServices;
        }

        public IActionResult Index(int pageNumber = 1, int pageSize = 5)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            //ModelState.Clear();
            var djelatnikID = HttpContext.Session.GetInt32("DjelatnikID");
            var djelatnikUloga = odobravanjeZahtjevaRepository.DohvatiDjelatnikovuUlogu((int)djelatnikID);
            if (djelatnikUloga == "Administrator")
            {
                TempData["uloga"] = "ADMIN";
            }
            else
                TempData["uloga"] = "DJELATNIK";
            var zahtjeviOdobravanjeSPaginacijom = new PaginacijaOdobravanjeZahtjeva();
            zahtjeviOdobravanjeSPaginacijom.odobravanjeZahtjeva = new OdobravanjeZahtjeva();

            if (HttpContext.Session.GetInt32(SessionStatus) != null)
            {
                var statusi = HttpContext.Session.GetInt32(SessionStatus);
                zahtjeviOdobravanjeSPaginacijom.odobravanjeZahtjeva.Status = statusi;
            }
            zahtjeviOdobravanjeSPaginacijom.odobravanjeZahtjeva.Statusi = odobravanjeZahtjevaRepository.DohvatiStatuse();
            odobravanjeZahtjevaRepository.DohvatiZahtjeveZaOdobravanjeSPaginacijom(zahtjeviOdobravanjeSPaginacijom, pageSize, pageNumber, (int)djelatnikID);

            return View(zahtjeviOdobravanjeSPaginacijom);
        }

        [HttpPost]
        public IActionResult Index(PaginacijaOdobravanjeZahtjeva zahtjeviOdobravanjeSPaginacijom, int pageNumber = 1, int pageSize = 5)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            var djelatnikID = HttpContext.Session.GetInt32("DjelatnikID");
            var djelatnik = new Djelatnik();
            if (djelatnikID != 0 && djelatnikID != null)
            {
                djelatnik = odobravanjeZahtjevaRepository.DohvatiDjelatnika((int)djelatnikID);
            }
            var djelatnikUloga = odobravanjeZahtjevaRepository.DohvatiDjelatnikovuUlogu((int)djelatnikID);
            if (djelatnikUloga == "Administrator")
            {
                TempData["uloga"] = "ADMIN";
            }
            else
                TempData["uloga"] = "DJELATNIK";
            if (zahtjeviOdobravanjeSPaginacijom.odobravanjeZahtjeva.Status == null)
            {
               
                zahtjeviOdobravanjeSPaginacijom.odobravanjeZahtjeva.Status = null;
                HttpContext.Session.Clear();
                HttpContext.Session.SetInt32("DjelatnikID", (int)djelatnikID);
            }
            
            if (zahtjeviOdobravanjeSPaginacijom.odobravanjeZahtjeva == null && zahtjeviOdobravanjeSPaginacijom.paginationModel == null)
            {
                zahtjeviOdobravanjeSPaginacijom.odobravanjeZahtjeva = new OdobravanjeZahtjeva();
            }
            if (zahtjeviOdobravanjeSPaginacijom.odobravanjeZahtjeva.RezervacijeOtkazivanje != null)
            {
               odobravanjeZahtjevaRepository.PotvrdiZahtjev(zahtjeviOdobravanjeSPaginacijom.odobravanjeZahtjeva);
                if (zahtjeviOdobravanjeSPaginacijom.odobravanjeZahtjeva.povratnaInfo != null)
                {
                    TempData["Info"] = zahtjeviOdobravanjeSPaginacijom.odobravanjeZahtjeva.povratnaInfo;
                }

            }
            if (zahtjeviOdobravanjeSPaginacijom.odobravanjeZahtjeva.Status != null)
            {
                HttpContext.Session.SetInt32(SessionStatus, (int)zahtjeviOdobravanjeSPaginacijom.odobravanjeZahtjeva.Status);
            }
            else
            {
                
            }
            odobravanjeZahtjevaRepository.DohvatiZahtjeveZaOdobravanjeSPaginacijom(zahtjeviOdobravanjeSPaginacijom, pageSize, pageNumber, (int)djelatnikID);
            zahtjeviOdobravanjeSPaginacijom.odobravanjeZahtjeva.Statusi = odobravanjeZahtjevaRepository.DohvatiStatuse();

   
            
            var datumi = odobravanjeZahtjevaRepository.DohvatiDatumOdobravanja(zahtjeviOdobravanjeSPaginacijom.odobravanjeZahtjeva);
            
            return View(zahtjeviOdobravanjeSPaginacijom);
        }
    }
}

AplikacijaDijeljenihRadnihMjesta/Controllers/ZahtjeviController.cs
using AplikacijaDijeljenihRadnihMjesta.Data;
using AplikacijaDijeljenihRadnihMjesta.Models.ViewModel;
using AplikacijaDijeljenihRadnihMjesta.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using cloudscribe.Pagination.Models;
using AplikacijaDijeljenihRadnihMjesta.Models.Paginacija;

namespace AplikacijaDijeljenihRadnihMjesta.Controllers
{
    public class ZahtjeviController : Controller
    {
        private PregledZahtjevaRepository pregledZahtjevaRepository;
        const string SessionTipZahtjeva = "_TipZahtjeva";
        const string SessionPocetniDatum = "_PocetniDatum";
        const string SessionKrajnjiDatum = "_KrajnjiDatum";
        public ZahtjeviController(AppDbContext db)
        {
            this.pregledZahtjevaRepository = new PregledZahtjevaRepository(db);
        }

        //[HttpGet]
        public IActionResult Index(int pageNumber = 1, int pageSize = 4)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            var djelatnikID = HttpContext.Session.GetInt32("DjelatnikID");
            var djelatnikUloga = pregledZahtjevaRepository.DohvatiDjelatnikovuUlogu((int)djelatnikID);
            if (djelatnikUloga == "Administrator")
            {
                TempData["uloga"] = "ADMIN";
            }
            else
                TempData["uloga"] = "DJELATNIK";

            var zahtjeviSPaginacijom = new PaginacijaZahtjev();
            zahtjeviSPaginacijom.pregledZahtjeva = new PregledZahtjevaVM();

            if (TempData["Resetiranje"] != null)
            {
                HttpContext.Session.SetString(SessionPocetniDatum, null);
                HttpContext.Session.SetString(SessionKrajnjiDatum, null);
            }
            if ( (pageNumber != 1 && HttpContext.Session.GetInt32(SessionTipZahtjeva) != 0) || (pageNumber == 1 && HttpContext.Session.GetInt32(SessionTipZahtjeva) != 0) && (HttpContext.Session.GetString(SessionPocetniDatum)==null || HttpContext.Session.GetString(SessionPocetniDatum) == "") && (HttpContext.Session.GetString(SessionKrajnjiDatum) == null || HttpContext.Session.GetString(SessionKrajnjiDatum) == ""))
            {
                var tipZahtjeva = HttpContext.Session.GetInt32(SessionTipZahtjeva);
                zahtjeviSPaginacijom.pregledZahtjeva.TipZahtjeva = tipZahtjeva;
                zahtjeviSPaginacijom.pregledZahtjeva.PocetniDatum = null;
                zahtjeviSPaginacijom.pregledZahtjeva.KrajnjiDatum = null;
            }
            if ((pageNumber != 1 || (pageNumber == 1 && HttpContext.Session.GetInt32(SessionTipZahtjeva) != 0)) && HttpContext.Session.GetString(SessionPocetniDatum) != null && HttpContext.Session.GetString(SessionPocetniDatum) != "" && HttpContext.Session.GetString(SessionKrajnjiDatum) != null && HttpContext.Session.GetString(SessionKrajnjiDatum) != "")
            {
                var pocetniDatum = HttpContext.Session.GetString(SessionPocetniDatum);
                var krajnjiDatum = HttpContext.Session.GetString(SessionKrajnjiDatum);
                var tipZahtjeva = HttpContext.Session.GetInt32(SessionTipZahtjeva);
                zahtjeviSPaginacijom.pregledZahtjeva.PocetniDatum = DateTime.Parse(pocetniDatum);
                zahtjeviSPaginacijom.pregledZahtjeva.KrajnjiDatum = DateTime.Parse(krajnjiDatum);
                zahtjeviSPaginacijom.pregledZahtjeva.TipZahtjeva = tipZahtjeva;
            }
            if ((pageNumber != 1 || (pageNumber == 1 && HttpContext.Session.GetInt32(SessionTipZahtjeva) == null)) && HttpContext.Session.GetString(SessionPocetniDatum) != null && HttpContext.Session.GetString(SessionPocetniDatum) != "" && HttpContext.Session.GetString(SessionKrajnjiDatum) != null && HttpContext.Session.GetString(SessionKrajnjiDatum) != "")
            {
                var pocetniDatum = HttpContext.Session.GetString(SessionPocetniDatum);
                var krajnjiDatum = HttpContext.Session.GetString(SessionKrajnjiDatum);
                zahtjeviSPaginacijom.pregledZahtjeva.PocetniDatum =DateTime.Parse(pocetniDatum);
                zahtjeviSPaginacijom.pregledZahtjeva.KrajnjiDatum = DateTime.Parse(krajnjiDatum);
                zahtjeviSPaginacijom.pregledZahtjeva.TipZahtjeva = null;
            }
            zahtjeviSPaginacijom.pregledZahtjeva.TipoviZahtjeva = pregledZahtjevaRepository.DohvatiTipoveZahtjeva();
            zahtjeviSPaginacijom = pregledZahtjevaRepository.DohvatiZahtjeve(zahtjeviSPaginacijom.pregledZahtjeva, (int)djelatnikID, pageSize, pageNumber);
            return View(zahtjeviSPaginacijom);
        }
        [HttpPost]
        public IActionResult Index(PaginacijaZahtjev zahtjeviSPaginacijom,  int pageNumber = 1, int pageSize = 4)
        {

            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            var djelatnikID = HttpContext.Session.GetInt32("DjelatnikID");
            var djelatnikUloga = pregledZahtjevaRepository.DohvatiDjelatnikovuUlogu((int)djelatnikID);
            if (djelatnikUloga == "Administrator")
            {
                TempData["uloga"] = "ADMIN";
            }
            else
                TempData["uloga"] = "DJELATNIK";
            if (zahtjeviSPaginacijom.pregledZahtjeva == null && zahtjeviSPaginacijom.paginationModel == null)
            {
                zahtjeviSPaginacijom.pregledZahtjeva = new PregledZahtjevaVM();
            }
            
            zahtjeviSPaginacijom  = pregledZahtjevaRepository.DohvatiZahtjeve(zahtjeviSPaginacijom.pregledZahtjeva, (int)djelatnikID, pageSize, pageNumber);
            if (zahtjeviSPaginacijom.pregledZahtjeva.povratnaInfo !=null)
            {
                TempData["Info"] = zahtjeviSPaginacijom.pregledZahtjeva.povratnaInfo;
            }
            else
            {
                if (zahtjeviSPaginacijom.pregledZahtjeva.TipZahtjeva != null && zahtjeviSPaginacijom.pregledZahtjeva.PocetniDatum == null 
                    && zahtjeviSPaginacijom.pregledZahtjeva.KrajnjiDatum == null)
                {
                    HttpContext.Session.SetInt32(SessionTipZahtjeva, (int)zahtjeviSPaginacijom.pregledZahtjeva.TipZahtjeva);
                }
                if (zahtjeviSPaginacijom.pregledZahtjeva.TipZahtjeva != null && zahtjeviSPaginacijom.pregledZahtjeva.PocetniDatum != null
                    && zahtjeviSPaginacijom.pregledZahtjeva.KrajnjiDatum != null)
                {
                    HttpContext.Session.SetInt32(SessionTipZahtjeva, (int)zahtjeviSPaginacijom.pregledZahtjeva.TipZahtjeva);
                    HttpContext.Session.SetString(SessionPocetniDatum, zahtjeviSPaginacijom.pregledZahtjeva.PocetniDatum.ToString());
                    HttpContext.Session.SetString(SessionKrajnjiDatum, zahtjeviSPaginacijom.pregledZahtjeva.KrajnjiDatum.ToString());
                }
                if (zahtjeviSPaginacijom.pregledZahtjeva.TipZahtjeva == null && zahtjeviSPaginacijom.pregledZahtjeva.PocetniDatum != null
                    && zahtjeviSPaginacijom.pregledZahtjeva.KrajnjiDatum != null)
                {
                    HttpContext.Session.SetString(SessionPocetniDatum, zahtjeviSPaginacijom.pregledZahtjeva.PocetniDatum.ToString());
                    HttpContext.Session.SetString(SessionKrajnjiDatum, zahtjeviSPaginacijom.pregledZahtjeva.KrajnjiDatum.ToString());
                }
                if (zahtjeviSPaginacijom.pregledZahtjeva.TipZahtjeva == null && zahtjeviSPaginacijom.pregledZahtjeva.PocetniDatum == null 
                    && zahtjeviSPaginacijom.pregledZahtjeva.KrajnjiDatum == null)
                {
                    HttpContext.Session.SetInt32(SessionTipZahtjeva, 0);
                    HttpContext.Session.SetString(SessionPocetniDatum, "");
                    HttpContext.Session.SetString(SessionKrajnjiDatum, "");
                }
            }

            zahtjeviSPaginacijom.pregledZahtjeva.TipoviZahtjeva = pregledZahtjevaRepository.DohvatiTipoveZahtjeva();
            

            return View(zahtjeviSPaginacijom);

        }

       
       

        public IActionResult Detalji(int zahtjevID)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            var djelatnikID = HttpContext.Session.GetInt32("DjelatnikID");
            var djelatnikUloga = pregledZahtjevaRepository.DohvatiDjelatnikovuUlogu((int)djelatnikID);
            if (djelatnikUloga == "Administrator")
            {
                TempData["uloga"] = "ADMIN";
            }
            else
                TempData["uloga"] = "DJELATNIK";
            var detalji=pregledZahtjevaRepository.DohvatiDetalje(zahtjevID);
            return View(detalji);
        }




       
    }
}

AplikacijaDijeljenihRadnihMjesta/Views/OdobravanjeZahtjeva/Index.cshtml
@model AplikacijaDijeljenihRadnihMjesta.Models.Paginacija.PaginacijaOdobravanjeZahtjeva
<partial name="Upozorenja" view-data="ViewData" />
<link rel="stylesheet" type="text/css" href="~/css/Stranica.css" media="screen" 7 />

@{

    ViewData["index"] = "ADMIN";
    ViewData["Controller"] = "OdobravanjeZahtjeva";
    ViewData["Action"] = "Index";
    ViewData["ImePrezime"] = TempData["ImePrezime"];
}

<div class="card p-3 mt-5" style=" overflow-x: auto;">

    <div class="col-12 pt-2">
        <h2 class="text-primary formTitle" style="text-align:center !important;">Zahtjevi za odobravanje</h2>
    </div>
    <form method="post" asp-controller="OdobravanjeZahtjeva" asp-action="Index">
        <div class="col-md-12" style="margin-bottom:10px">
            <select class="form-select" style="display:inline-block;width:200px;" asp-for="@Model.odobravanjeZahtjeva.Status" asp-items="@Model.odobravanjeZahtjeva.Statusi">
                <option selected> Svi statusi </option>
            </select>
            <input type="submit" name="submitButton1" style="font-size: 1em !important; margin-bottom:4.5px;margin-left:20px;display:inline-block" class="btn btn-primary" value="Filtriraj" />

            

        </div>
    </form>
    <form method="post" asp-controller="OdobravanjeZahtjeva" asp-action="Index">
        @if (Model.odobravanjeZahtjeva.RezervacijeOtkazivanje != null && Model.odobravanjeZahtjeva.RezervacijeOtkazivanje.Count() > 0)
        {
            <table class="table tableCss table-bordered table-striped" style="width:100%">
                <thead>
                    <tr>
                        <th>
                            Ime i prezime
                        </th>
                        <th>
                            Tip zahtjeva
                        </th>
                        <th>
                            Datum
                        </th>
                        <th>
                            Dodatne informacije
                        </th>
                        <th>
                            Komentar na zahtjev
                        </th>
                        <th>
                            Odobreno
                        </th>
                        <th>
                            Otkazano
                        </th>


                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < @Model.odobravanjeZahtjeva.RezervacijeOtkazivanje.Count(); i++)
                    {
                        @Html.HiddenFor(m => m.odobravanjeZahtjeva.RezervacijeOtkazivanje[i].Id)
                        @Html.HiddenFor(m => m.odobravanjeZahtjeva.RezervacijeOtkazivanje[i].ZahtjevId)
                        <tr>
                            <td id="items" width="20%" style="text-align:center;vertical-align: middle;">@Html.HiddenFor(m => m.odobravanjeZahtjeva.RezervacijeOtkazivanje[i].DjelatnikEmail) @Model.odobravanjeZahtjeva.RezervacijeOtkazivanje[i].ImeIPrezime</td>
                            <td id="items" width="20%" style="text-align:center;vertical-align: middle;">@Html.HiddenFor(m => m.odobravanjeZahtjeva.RezervacijeOtkazivanje[i].TipZahtjeva) @Model.odobravanjeZahtjeva.RezervacijeOtkazivanje[i].TipZahtjeva</td>
                            <td id="items" width="30%" style="text-align:center;vertical-align: middle;">@Html.HiddenFor(m => m.odobravanjeZahtjeva.RezervacijeOtkazivanje[i].Datum) @Model.odobravanjeZahtjeva.RezervacijeOtkazivanje[i].Datum.ToShortDateString()</td>
                            <td style=" text-align: center; vertical-align: middle">
                                @Html.TextAreaFor(m => m.odobravanjeZahtjeva.RezervacijeOtkazivanje[i].RazlogOtkazivanja, new
                           {
                               disabled = "disabled",
                               @style = "min-height:50px;color:black ;width: 200px;font-size:12px; background:smoke;padding:5px;"
                           })

                            </td>
                            @if (Model.odobravanjeZahtjeva.RezervacijeOtkazivanje[i].Komentar != null || (Model.odobravanjeZahtjeva.RezervacijeOtkazivanje[i].Status=="Odobreno") || Model.odobravanjeZahtjeva.RezervacijeOtkazivanje[i].Status == "Otkazano")
                            {
                                <td style=" text-align: center; vertical-align: middle">
                                    @Html.TextAreaFor(m => m.odobravanjeZahtjeva.RezervacijeOtkazivanje[i].Komentar, new
                               {

                                        disabled = "disabled",
                                   @style = "min-height:50px;color:black;width: 200px; padding:5px; font-size:12px; background:smoke; "
                               })
                                </td>
                            }
                            else
                            {
                                <td style=" text-align: center; vertical-align: middle">
                                    @Html.TextAreaFor(m => m.odobravanjeZahtjeva.RezervacijeOtkazivanje[i].Komentar, new
                               {
                                   @style = "min-height:50px;width: 200px; font-size:12px; "
                               })
                                </td>
                            }


                            <td class="text-center" style=" text-align: center; vertical-align: middle;padding-right: 15px;padding-left: 15px;">
                                <div class="w-70 btn-group" role="group">

                                    @if (Model.odobravanjeZahtjeva.RezervacijeOtkazivanje[i].Status == "Odobreno" || Model.odobravanjeZahtjeva.RezervacijeOtkazivanje[i].Status == "Otkazano")
                                    {

                                        @Html.HiddenFor(m => m.odobravanjeZahtjeva.RezervacijeOtkazivanje[i].OdgovorCheckBoxOdobreno)
                                        if (Model.odobravanjeZahtjeva.RezervacijeOtkazivanje[i].Status == "Odobreno")
                                        {
                                            <i class="fas fa-check" style="font-size: 20px;color: #006700ad;"></i>
                                        }

                                    }
                                    else
                                    {
                                        @Html.CheckBoxFor(m => m.odobravanjeZahtjeva.RezervacijeOtkazivanje[i].OdgovorCheckBoxOdobreno, new
                                       {
                                       style = "width:22px;height:22px; background:green"
                                        })

                                    }
                                </div>
                            </td>
                            <td class="text-center" style=" text-align: center; vertical-align: middle;padding-right: 15px;padding-left: 15px;">
                                <div class="w-70 btn-group" role="group">
                                    @if (Model.odobravanjeZahtjeva.RezervacijeOtkazivanje[i].Status == "Otkazano" || Model.odobravanjeZahtjeva.RezervacijeOtkazivanje[i].Status == "Odobreno")
                                    {
                                        @Html.HiddenFor(m => m.odobravanjeZahtjeva.RezervacijeOtkazivanje[i].OdgovorCheckBoxOtkazano)

                                        if (Model.odobravanjeZahtjeva.RezervacijeOtkazivanje[i].Status == "Otkazano")
                                        {
                                            <i class="fas fa-times" style="font-size: 26.8px; color: #d23131c7"></i>
                                        }
                                    }

                                    else
                                    {
                                        @Html.CheckBoxFor(m => m.odobravanjeZahtjeva.RezervacijeOtkazivanje[i].OdgovorCheckBoxOtkazano, new
                                        {
                                            style = "width:22px;height:22px"
                                        })
                                    }


                                </div>
                            </td>

                        </tr>
                    }

                </tbody>
            </table>

            <div class="col-md-12" style="margin-bottom:10px">
                <input type="submit" style="font-size: 1em !important;float:right" class="btn btn-success" value="Potvrdi zahtjev" />
            </div>
        }
        else
        {
            <br /><br />
            <p>Nema zahtjeva za odobriti ili otkazati!</p>
        }
    </form>
    <form style="align-content:center" method="post" asp-controller="Zahtjevi" asp-action="Index">

        <partial name="_Pagination" view-data="ViewData" model="Model" />

    </form>


</div>


@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }

}