AplikacijaDijeljenihRadnihMjesta/Controllers/GradController.cs
using AplikacijaDijeljenihRadnihMjesta.Data;
using AplikacijaDijeljenihRadnihMjesta.Models.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AplikacijaDijeljenihRadnihMjesta.Repository
{
    public class GradController : Controller
    {
        private GradRepository gradRepository;
        const string SessionGrad = "_GradID";

        public GradController(AppDbContext db)
        {
            this.gradRepository = new GradRepository(db);
        }

        [HttpGet]
        public IActionResult Index()
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            return View(gradRepository.DohvatiListuGradova());
        }

        //GET-CREATE
        public IActionResult Create()
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            return View();
        }

        //POST-CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(GradVM grad)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            if (ModelState.IsValid)
            {
                if (gradRepository.DodajNoviGrad(grad))
                {
                    TempData["Uspješno"] = "Uspješno dodan novi grad!";
                }
                else
                {
                    TempData["Neuspješno"] = "Grad već postoji!";
                }
            }
            ModelState.Clear();
            var noviGrad = new GradVM();
            return View(noviGrad);
        }


        //GET-EDIT
        public IActionResult Edit(int id)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            if (id != 0)
            {
                var grad = gradRepository.DohvatiGradPoId(id);
                HttpContext.Session.SetInt32(SessionGrad, grad.Id);
                return View(new GradVM { Naziv=grad.Naziv, Oznaka=grad.Oznaka });
            }
            return NotFound();
        }

        //POST-EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(GradVM grad)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            if (ModelState.IsValid)
            {
                var gradId = HttpContext.Session.GetInt32(SessionGrad);
                if (gradRepository.EditGrad(grad, (int)gradId))
                {
                    TempData["Uspješno"] = "Uspješno promijenjen naziv grada!";
                }
                else
                {
                    TempData["Neuspješno"] = "Neuspješna promjena naziva grada! Provjerite postoji li već grad s tim imenom.";
                }
            }
            ModelState.Clear();
            return View(grad);
        }

        //GET-DELETE
        public IActionResult Delete(int id)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            if (ModelState.IsValid)
            {
                if (gradRepository.IzbrisiGrad(id))
            {
                TempData["Uspješno"] = "Uspješno izbrisan grad!";
            }
            else
            {
                TempData["Neuspješno"] = "Neuspješno brisanje grada jer postoje povezane lokacije!";
            }
            }
            ModelState.Clear();
            return RedirectToAction("Index");
            
        }
    }
}

AplikacijaDijeljenihRadnihMjesta/Controllers/LokacijaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AplikacijaDijeljenihRadnihMjesta.Data;
using AplikacijaDijeljenihRadnihMjesta.Models;
using AplikacijaDijeljenihRadnihMjesta.Models.ViewModel;
using AplikacijaDijeljenihRadnihMjesta.Repository;
using Microsoft.AspNetCore.Http;

namespace AplikacijaDijeljenihRadnihMjesta.Controllers
{
    public class LokacijaController : Controller
    {
        private LokacijaRepository lokacijaRepository;
        const string SessionOrgJedinica = "_OrgJedinicaID";
        const string SessionOrgJedinicaNaziv = "_OrgJedinicaNaziv";
        const string SessionStaraOrgJedinicaID = "_StaraOrgJedinicaID";


        public LokacijaController(AppDbContext db)
        {
            this.lokacijaRepository = new LokacijaRepository(db);
        }
        [HttpGet]
        public IActionResult Index(int? orgJedID, string nazivOrgJed)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            if (orgJedID != 0 && orgJedID != null)
            {
                HttpContext.Session.SetInt32(SessionOrgJedinica, (int)orgJedID);
                TempData["OrgJedID"] = orgJedID;
                TempData["NazivOrgJed"] = lokacijaRepository.DohvatiNazivOrgJedinice((int)orgJedID);
                HttpContext.Session.SetString(SessionOrgJedinicaNaziv, lokacijaRepository.DohvatiNazivOrgJedinice((int)orgJedID));
                return View(lokacijaRepository.DohvatiListuLokacija((int)orgJedID));
            }
            else
            {
                TempData["OrgJedID"] = null;
                var lok = new LokacijaFilter();
                lok = lokacijaRepository.DohvatiListuLokacija();
                foreach (var org in lok.ListaLokacija)
                {
                    var lista= lokacijaRepository.DohvatiOrgJedNaLokaciji(org.Id);
                    foreach (var l in lista)
                    {
                        org.ListaOrganizacijskihJedinica += "-";
                        org.ListaOrganizacijskihJedinica +=( l + "\r\n");
                        //org.ListaOrganizacijskihJedinica += System.Environment.NewLine;
                    }
                    org.ListaOrganizacijskihJedinica = string.Join(", ",lista);

                    //org.ListaOrganizacijskihJedinica.Remove(org.ListaOrganizacijskihJedinica.Length - 2);
                }
                return View(lok);
            }
                
        }
        [HttpPost]
        public IActionResult Index(int? orgJedID, int? GradID)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            if (orgJedID != 0 && GradID == null)
            {
                var nazivOrgJed = HttpContext.Session.GetString(SessionOrgJedinicaNaziv);
                HttpContext.Session.SetInt32(SessionOrgJedinica, (int)orgJedID);
                TempData["OrgJedID"] = orgJedID;
                TempData["NazivOrgJed"] = nazivOrgJed;
                return View(lokacijaRepository.DohvatiListuLokacija((int)orgJedID));
            }
            else if (orgJedID == 0 && GradID != null )
            {
                return View(lokacijaRepository.DohvatiListuLokacijaFiltriranuPoGradu((int)GradID));
            }
            else if (orgJedID != 0 && GradID != null )
            {
                var nazivOrgJed=HttpContext.Session.GetString(SessionOrgJedinicaNaziv);
                TempData["OrgJedID"] = orgJedID;
                TempData["NazivOrgJed"] = nazivOrgJed;
                return View(lokacijaRepository.DohvatiListuLokacija((int)orgJedID, (int)GradID));
            }
            else
                return View(lokacijaRepository.DohvatiListuLokacija());
        }

        //GET-CREATE
        public IActionResult Create(int? orgJedID)
        {
            TempData["OrgJedID"] = HttpContext.Session.GetInt32(SessionOrgJedinica);
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            var lista = new LokacijaVM();
            lokacijaRepository.DohvatiGradove(lista);
            if (orgJedID != 0)
            {
                lokacijaRepository.DohvatiOrgJedinice(lista,(int)orgJedID);
            }
            else
            {
                lokacijaRepository.DohvatiOrgJedinice(lista);
            }
            return View(lista);
        }

        //POST-CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(LokacijaVM lokacija)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            if (lokacijaRepository.DodajNovuLokaciju(lokacija))
            {
                TempData["OrgJedID"] = HttpContext.Session.GetInt32(SessionOrgJedinica);
                TempData["Uspješno"] = "Uspješno dodana nova lokacija!";
            }
            else
            {
                TempData["Neuspješno"] = "Lokacija već postoji!";
            }
            ModelState.Clear();
            var lista = new LokacijaVM();
            lista.Gradovi = lokacijaRepository.DohvatiGradove();
            if (TempData["OrgJedID"] != null)
            {
                lokacijaRepository.DohvatiOrgJedinice(lista, (int)TempData["OrgJedID"]);
            }
            else
                lokacijaRepository.DohvatiOrgJedinice(lista);
            return View(lista);
        }

        //GET-DELETE
        public IActionResult Delete(int? id, int? orgJedID)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            TempData["OrgJedID"] = HttpContext.Session.GetInt32(SessionOrgJedinica);
            var nazivOrgJed = HttpContext.Session.GetString(SessionOrgJedinicaNaziv);
            if (ModelState.IsValid)
            {
                if (orgJedID != null)
                {
                    if (lokacijaRepository.IzbrisiLokacijuUnutarOrgJedinice((int)id, (int)orgJedID))
                    {
                        TempData["Uspješno"] = $"Uspješno izbrisana lokacija iz organizacijske jedinice: {nazivOrgJed}!";
                    }
                    else
                    {
                        TempData["Neuspješno"] = $"Neuspješno brisanje lokacije iz organizacijske jedinice:{nazivOrgJed} !";
                    }
                }
                else
                {
                    if (lokacijaRepository.IzbrisiLokaciju((int)id))
                    {
                        TempData["Uspješno"] = "Uspješno izbrisana lokacija!";
                    }
                    else
                    {
                        TempData["Neuspješno"] = "Neuspješno brisanje lokacije, pogledajte postoje li radna mjesta na toj lokaciji prije brisanja !";
                    }
                }
            }
            ModelState.Clear();
            if (orgJedID != 0)
            {
                return RedirectToAction("Index", new
                {
                    orgJedID = orgJedID
                });
            }
            return RedirectToAction("Index");
        }

        //public IActionResult DohvatiOrgJed(int? id, int? orgJedID)
        //{
        //    TempData["OrgJedID"] = HttpContext.Session.GetInt32(SessionOrgJedinica);
        //    var nazivOrgJed = HttpContext.Session.GetString(SessionOrgJedinicaNaziv);

        //    var lista=lokacijaRepository.DohvatiOrgJedNaLokaciji((int)id);
        //    var orgJedinice = new LokacijaFilter();
        //    orgJedinice.ListaOrganizacijskihJedinica = lista;
        //    if (orgJedID != 0)
        //    {
        //        return RedirectToAction("Index", new
        //        {
        //            orgJedID = orgJedID
        //        });
        //    }
        //    return RedirectToAction("Index");
        //}

        //GET-EDIT
        public IActionResult Edit(int? id, int? orgJedID)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            var lokacija = lokacijaRepository.DohvatiLokacijuPoId(id); //lokacija iz baze
            var gradovi = lokacijaRepository.DohvatiGradove();
            if (id != null)
            {
                if (orgJedID != 0 && orgJedID!=null)
                {
                    HttpContext.Session.SetInt32(SessionStaraOrgJedinicaID, (int)orgJedID);
                    var OrgJed = lokacijaRepository.DohvatiOrgJedinice((int)orgJedID);
                    TempData["OrgJedID"] = HttpContext.Session.GetInt32(SessionOrgJedinica);
                    var lokacijaModel = new LokacijaVM{ Id = lokacija.Id, Adresa = lokacija.Adresa, Gradovi = gradovi, Grad = lokacijaRepository.DohvatiNazivGrada(lokacija), OrgJedinica = lokacijaRepository.DohvatiNazivOrgJedinice((int)orgJedID), OrgJedinice = OrgJed };
                    lokacijaModel = lokacijaRepository.DohvatiPripadajuceOrgJedinice(lokacijaModel);
                    return View(lokacijaModel);
                }
                else
                {
                    var lokacijaModel = new LokacijaVM{ Id = lokacija.Id, Adresa = lokacija.Adresa, Gradovi = gradovi, Grad = lokacijaRepository.DohvatiNazivGrada(lokacija), OrgJedinica = lokacijaRepository.DohvatiNazivOrgJedinicePoID(lokacija.Id), OrgJedinice = lokacijaRepository.DohvatiOrgJedinice() };
                    lokacijaModel = lokacijaRepository.DohvatiPripadajuceOrgJedinice(lokacijaModel);
                    return View(lokacijaModel);
                    
                }
            }
            return NotFound();
        }



        //POST-EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(LokacijaVM lokacija)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            TempData["OrgJedID"] = HttpContext.Session.GetInt32(SessionOrgJedinica);
            var orgJedID = TempData["OrgJedID"];
            if (lokacijaRepository.EditLokacija(lokacija))

AplikacijaDijeljenihRadnihMjesta/Controllers/TipLaptopaController.cs
using AplikacijaDijeljenihRadnihMjesta.Data;
using AplikacijaDijeljenihRadnihMjesta.Models;
using AplikacijaDijeljenihRadnihMjesta.Models.ViewModel;
using AplikacijaDijeljenihRadnihMjesta.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AplikacijaDijeljenihRadnihMjesta.Controllers
{
    public class TipLaptopaController : Controller
    {
        private TipLaptopaRepository tipLaptopaRepository;

        public TipLaptopaController(AppDbContext db)
        {
            this.tipLaptopaRepository = new TipLaptopaRepository(db);
        }
        [HttpGet]
        public IActionResult Index()
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            return View(tipLaptopaRepository.DohvatiListuTipovaLaptopa());
        }

        //GET-CREATE
        public IActionResult Create()
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            return View();
        }

        //POST-CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(TipLaptopaVM tipLaptopa)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            if (ModelState.IsValid)
            {
                if (tipLaptopaRepository.DodajNoviTipLaptopa(tipLaptopa))
                {
                    TempData["Uspješno"] = "Uspješno dodan novi model laptopa!";
                }
                else
                {
                    TempData["Neuspješno"] = "Željeni model već postoji!";
                }
            }
            ModelState.Clear();
            var noviLaptop = new TipLaptopaVM();
            return View(noviLaptop);
        }


        //GET-EDIT
        public IActionResult Edit(int? id)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            if (id != null)
            {
                var tipLaptopa = tipLaptopaRepository.DohvatiTipLaptopaPoId(id);

                return View(new TipLaptopaVM { Id = tipLaptopa.Id, Model = tipLaptopa.Model });
            }
            return NotFound();
        }

        //POST-EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(TipLaptopaVM tipLaptopa)
        {

            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            if (ModelState.IsValid)
            {
                if (tipLaptopaRepository.EditTipLaptopa(tipLaptopa))
                {
                    TempData["Uspješno"] = "Uspješno promijenjen naziv modela laptopa!";
                }
                else
                {
                    TempData["Neuspješno"] = "Neuspješna promjena naziva modela! Pogledajte postoji li takav model laptopa.";
                }
            }
            ModelState.Clear();
            return View(tipLaptopa);
        }

        //GET-DELETE
        [HttpPost]
        public IActionResult Delete(int? id)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            if (id == null)
            { 
                return NotFound();
            }
            else
            {

                if (tipLaptopaRepository.IzbrisiTipLaptopa((int)id))
                {
                    TempData["Uspješno"] = "Uspješno brisanje modela laptopa!";
                }
                else {
                    TempData["Neuspješno"] = "Neuspješna brisanje modela jer postoje djelatnici koji ga koriste, dodijelite im drugi model laptopa pa onda obrišite!";
                    
                }
                //ModelState.Clear();
                return RedirectToAction("Index");
            }
        }


    }
}

AplikacijaDijeljenihRadnihMjesta/Views/Shared/NavigacijskaTrakaPartialView.cshtml
<link rel="stylesheet" type="text/css" href="~/css/NavigacijskaTraka.css" media="screen" 7 />
@{

    var imePrezime=ViewData["ImePrezime"];
}

    <nav class="navbar navbar-expand-lg navbar-light ">
        @if ((string) ViewData["index"] == "ADMIN")
            {
        <a class="navbar-brand" href="@Url.Action("Pocetna", "Autentifikacija")"> <img src="~/Slike/laptopIcon.png" style="width: 40px;margin-right:10px;" class=" row-link" data-toggle="tooltip" title="Pritisni za uređivanje podataka!" data-placement="right">Dijeljena radna mjesta</a>
    }
    else
    {
<a class="navbar-brand"><img src="~/Slike/laptopIcon.png" style="width: 40px;margin-right:10px;" class=" row-link" data-toggle="tooltip" title="Pritisni za uređivanje podataka!" data-placement="right">Dijeljena radna mjesta</a>
}

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active ">
                    <a class="nav-link" asp-area="" asp-controller="Zahtjevi" asp-action="Index">Pregled zahtjeva <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" asp-area="" asp-controller="Rezervacije" asp-action="Index">Rezervacija <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" asp-area="" asp-controller="Otkazivanje" asp-action="Index">Otkazivanje <span class="sr-only">(current)</span></a>
                </li>
                @if ((string)ViewData["index"] == "ADMIN")
                {
                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="OdobravanjeZahtjeva" asp-action="Index">Odobravanje <span class="sr-only">(current)</span></a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Ostalo
                        </a>

                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-area="" asp-controller="Djelatnik" asp-action="Index">Djelatnik</a>
                            <a class="dropdown-item" asp-area="" asp-controller="TipLaptopa" asp-action="Index">Tip laptopa</a>
                            <a class="dropdown-item" asp-area="" asp-controller="RadnoMjesto" asp-action="Index">Radno mjesto</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Grad" asp-action="Index">Grad</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Lokacija" asp-action="Index">Lokacija</a>
                            <a class="dropdown-item" asp-area="" asp-controller="OrganizacijskaJedinica" asp-action="Index">Organizacijska jedinica</a>
                            @*<a class="dropdown-item" asp-area="" asp-controller="OdobravanjeZahtjeva" asp-action="Index">Odobravanje zahtjeva</a>*@

                        </div>

                    </li>
                }
                <li class="nav-item username"> <a> <label style="color:white; vertical-align:middle;"> @imePrezime</label></a></li>

                <li class="nav-item active">
                    @*<label> @imePrezime</label>*@
                    <a class="nav-link" style="text-align:right;display:inline-block;" asp-controller="Autentifikacija" asp-action="Prijava"> <i class="fas fa-sign-out-alt" style="font-size:20px"></i> <span class="sr-only">(current)</span></a>
                </li>

            </ul>
        </div>
    </nav>

AplikacijaDijeljenihRadnihMjesta/Views/Shared/Upozorenja.cshtml
@if ((string)TempData["Uspješno"] != null)
{
    <div class="alert alert-success" style="margin-top:10px!important">
        <strong>@TempData["Uspješno"]</strong>
    </div>
}
@if ((string)TempData["Neuspješno"] != null)
{
    <div class="alert alert-danger" style="margin-top:10px!important;">
        <strong>@TempData["Neuspješno"]</strong>
    </div>
}
 @if ((string)TempData["Info"] != null)
{
    <div class="alert alert-warning" style="margin-top:10px!important;">
        <strong>@TempData["Info"]</strong>
    </div>
}

AplikacijaDijeljenihRadnihMjesta/Views/Shared/_Layout.cshtml
<!DOCTYPE html>


<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AplikacijaDijeljenihRadnihMjesta</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="~/fontawesome/css/all.css" />
</head>
<body>
  
    <partial name="NavigacijskaTrakaPartialView" view-data="ViewData" />

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>
<footer class="border-top footer text-muted" style="justify-content:center;text-align:center">
    <div class="container ">
        &copy; 2021 - AplikacijaDijeljenihRadnihMjesta
    </div>
</footer>

AplikacijaDijeljenihRadnihMjesta/Views/Shared/_Pagination.cshtml
<link rel="stylesheet"  type="text/css" href="~/css/Stranica.css" media="screen" 7 />
<cs-pager style:"justify-content: center;" itemid="pagination"
          cs-paging-pagenumber=(int)Model.paginationModel.PageNumber
          cs-paging-totalitems=(int)Model.paginationModel.TotalItems
          cs-paging-pagesize=Model.paginationModel.PageSize
          cs-pagenumber-param="pagenumber"
          asp-controller=@ViewData["Controller"]
          as-action=@ViewData["Action"] 
          cs-pager-li-current-class="page-item active "
          cs-pager-li-other-class="page-item"
          cs-pager-li-non-active-class="page-item-disabled"
          cs-pager-link-current-class="page-link"
          cs-pager-link-other-class="page-link"></cs-pager>