AplikacijaDijeljenihRadnihMjesta/Models/RadnoMjesto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AplikacijaDijeljenihRadnihMjesta.Models
{
    public class RadnoMjesto
    {
        public int Id
        {
            get; set;
        }

        public string Sifra
        {
            get; set;
        }

        public TipLaptopa TipLaptopa
        {
            get; set;
        }

        public int TipLaptopaId
        {
            get; set;
        }
        public Lokacija Lokacija
        {
            get; set;
        }

        public int LokacijaId
        {
            get; set;
        }

        public bool Onemoguceno { get; set; }
    }
    }

AplikacijaDijeljenihRadnihMjesta/Controllers/RadnoMjestoController.cs
using Microsoft.AspNetCore.Mvc;
using AplikacijaDijeljenihRadnihMjesta.Data;
using AplikacijaDijeljenihRadnihMjesta.Models.ViewModel;
using AplikacijaDijeljenihRadnihMjesta.Repository;
using Microsoft.AspNetCore.Http;
using AplikacijaDijeljenihRadnihMjesta.Models.Paginacija;

namespace AplikacijaDijeljenihRadnihMjesta.Controllers
{
    public class RadnoMjestoController : Controller
    {
        private RadnoMjestoRepository radnoMjestoRepository;
        const string SessionLokacija = "_LokacijaID";
        const string SessionRadnoMjesto = "_RadnoMjestoIDPrijeEdit";
        const string SessionOrgJedID = "_OrgJedinicaID";
        const string SessionModelLaptopa = "_ModelLaptopaID";

        public RadnoMjestoController(AppDbContext db)
        {
            this.radnoMjestoRepository = new RadnoMjestoRepository(db);
        }

        [HttpGet]
        public IActionResult Index(int LokacijaId, int? orgJedID, int pageNumber = 1, int pageSize = 4)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            var radnaMjestaSPaginacijom = new PaginacijaRadnoMjesto();
            radnaMjestaSPaginacijom.radnoMjestoFilter = new RadnoMjestoFilter();
            TempData["LokacijaID"] = LokacijaId;
            var modelLaptopa = 0;
            HttpContext.Session.SetInt32(SessionLokacija, (int)LokacijaId);
            if (orgJedID != null && orgJedID != 0)
            {
                if (HttpContext.Session.GetInt32(SessionModelLaptopa) != null && HttpContext.Session.GetInt32(SessionModelLaptopa) != 0)
                {
                    modelLaptopa = (int)HttpContext.Session.GetInt32(SessionModelLaptopa);
                    radnaMjestaSPaginacijom.radnoMjestoFilter.TipLaptopaID = (int)modelLaptopa;
                }

                HttpContext.Session.SetInt32(SessionOrgJedID, (int)orgJedID);
                TempData["OrgJedID"] = orgJedID;
            }

            if (LokacijaId != 0)
            {
                if (HttpContext.Session.GetInt32(SessionModelLaptopa) != null && HttpContext.Session.GetInt32(SessionModelLaptopa) != 0)
                {
                    modelLaptopa = (int)HttpContext.Session.GetInt32(SessionModelLaptopa);
                    radnaMjestaSPaginacijom.radnoMjestoFilter.TipLaptopaID = (int)modelLaptopa;
                }
                if (modelLaptopa != 0)
                {
                    radnaMjestaSPaginacijom = radnoMjestoRepository.DohvatiListuRadnihMjesta_LokacijiDI_TipoviLaptopa(radnaMjestaSPaginacijom, (int)LokacijaId, (int)modelLaptopa, pageSize, pageNumber);
                }
                else
                    radnaMjestaSPaginacijom = radnoMjestoRepository.DohvatiListuRadnihMjestapoLokacijiDI(radnaMjestaSPaginacijom, (int)LokacijaId, pageSize, pageNumber);
            }

            else
            {
                if (HttpContext.Session.GetInt32(SessionModelLaptopa) != null && HttpContext.Session.GetInt32(SessionModelLaptopa) != 0)
                {
                    modelLaptopa = (int)HttpContext.Session.GetInt32(SessionModelLaptopa);
                    radnaMjestaSPaginacijom.radnoMjestoFilter.TipLaptopaID = (int)modelLaptopa;
                }
                if (modelLaptopa != 0)
                {
                    radnaMjestaSPaginacijom = radnoMjestoRepository.DohvatiListuRadnihMjestailtriranihPoTipuLaptopa(radnaMjestaSPaginacijom, (int)modelLaptopa, pageSize, pageNumber);
                }
                else
                    radnaMjestaSPaginacijom = radnoMjestoRepository.DohvatiListuRadnihMjesta(radnaMjestaSPaginacijom, pageSize, pageNumber);
            }
            if (modelLaptopa != 0)
            {
                radnaMjestaSPaginacijom.radnoMjestoFilter.TipLaptopaID = (int)modelLaptopa;
            }
                return View(radnaMjestaSPaginacijom);
        }
        [HttpPost]
        public IActionResult Index(PaginacijaRadnoMjesto radnaMjestaSPaginacijom,  int? lokacijaID, int? tipLaptopaID, int pageNumber = 1, int pageSize = 4)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            if (lokacijaID != 0 && radnaMjestaSPaginacijom.radnoMjestoFilter.TipLaptopaID == 0)
            {
                HttpContext.Session.SetInt32(SessionLokacija, (int)lokacijaID);
                HttpContext.Session.SetInt32(SessionModelLaptopa, 0);
                TempData["LokacijaID"] = lokacijaID;
                TempData["AdresaLokacije"] = radnoMjestoRepository.DohvatiAdresuLokacije((int)lokacijaID);
                radnaMjestaSPaginacijom = radnoMjestoRepository.DohvatiListuRadnihMjestapoLokacijiDI(radnaMjestaSPaginacijom, (int)lokacijaID, pageSize, pageNumber);
                TempData["OrgJedID"] = HttpContext.Session.GetInt32(SessionOrgJedID);
                return View(radnaMjestaSPaginacijom);

            }
            else if (lokacijaID == 0 && radnaMjestaSPaginacijom.radnoMjestoFilter.TipLaptopaID!=0)
            {
                var tip = radnaMjestaSPaginacijom.radnoMjestoFilter.TipLaptopaID;
                HttpContext.Session.SetInt32(SessionModelLaptopa, radnaMjestaSPaginacijom.radnoMjestoFilter.TipLaptopaID);
                radnaMjestaSPaginacijom = radnoMjestoRepository.DohvatiListuRadnihMjestailtriranihPoTipuLaptopa(radnaMjestaSPaginacijom, (int)tipLaptopaID, pageSize, pageNumber);
                radnaMjestaSPaginacijom.radnoMjestoFilter.TipLaptopaID = tip;
                return View(radnaMjestaSPaginacijom);
            }
            else if (lokacijaID != 0 && radnaMjestaSPaginacijom.radnoMjestoFilter.TipLaptopaID != 0)
            {
                HttpContext.Session.SetInt32(SessionModelLaptopa, radnaMjestaSPaginacijom.radnoMjestoFilter.TipLaptopaID);
                TempData["LokacijaID"] = lokacijaID;
                TempData["OrgJedID"] = HttpContext.Session.GetInt32(SessionOrgJedID);
                TempData["AdresaLokacije"] = radnoMjestoRepository.DohvatiAdresuLokacije((int)lokacijaID);
                radnaMjestaSPaginacijom = radnoMjestoRepository.DohvatiListuRadnihMjesta_LokacijiDI_TipoviLaptopa(radnaMjestaSPaginacijom, (int)lokacijaID, (int)tipLaptopaID, pageSize, pageNumber);
                radnaMjestaSPaginacijom.radnoMjestoFilter.TipLaptopaID = radnaMjestaSPaginacijom.radnoMjestoFilter.TipLaptopaID;
                return View(radnaMjestaSPaginacijom);
            }
            else
            {
                HttpContext.Session.SetInt32(SessionModelLaptopa, 0);
                radnaMjestaSPaginacijom = radnoMjestoRepository.DohvatiListuRadnihMjesta(radnaMjestaSPaginacijom, pageSize, pageNumber);
                radnaMjestaSPaginacijom.radnoMjestoFilter.TipLaptopaID = 0;
                return View(radnaMjestaSPaginacijom);
            }
                
        }

        //GET-CREATE
        public IActionResult Create(int LokacijaId, int? orgJedID)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            var lista = new RadnoMjestoVM();
            lista.tipoviLaptopa = radnoMjestoRepository.DohvatiTipoveLaptopa();

            if (LokacijaId != 0)
            {
                TempData["LokacijaID"] = (int)HttpContext.Session.GetInt32(SessionLokacija);
                lista.Lokacije= radnoMjestoRepository.DohvatiLokacije(LokacijaId);
                lista.LokacijaId = LokacijaId;
            }
            if (LokacijaId == 0)
            {
                lista.Lokacije = radnoMjestoRepository.DohvatiLokacije();
            }
            if (orgJedID != 0 && orgJedID != null)
            {
                TempData["OrgJedID"] = orgJedID;
            }
            return View(lista);
        }

        //POST-CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(RadnoMjestoVM radnoMjesto, int? orgJedID, int? lokacijaID)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            if (radnoMjesto.LokacijaId != 0)
            {
                radnoMjesto.LokacijaId = (int)HttpContext.Session.GetInt32(SessionLokacija);
                TempData["LokacijaID"] = radnoMjesto.LokacijaId; //za back
            }
            else
            {
                //TempData["LokacijaID"] = Int32.Parse(radnoMjesto.Lokacija);
            }
            TempData["OrgJedID"]= HttpContext.Session.GetInt32(SessionOrgJedID);
            if (ModelState.IsValid)
            {
                if (radnoMjesto.LokacijaId != 0)
                {
                    if (radnoMjestoRepository.DodajNovoRadnoMjesto_LokacijaID(radnoMjesto))
                    {
                        TempData["Uspješno"] = $"Uspješno dodano novo radno mjesto {radnoMjesto.Sifra}!";
                    }
                    else
                    {
                        TempData["Neuspješno"] = "Radno mjesto već postoji!";
                    }
                }
                else
                {
                    if (radnoMjestoRepository.DodajNovoRadnoMjesto(radnoMjesto))
                    {
                        TempData["Uspješno"] = $"Uspješno dodano novo radno mjesto {radnoMjesto.Sifra}!";
                    }
                    else
                    {
                        TempData["Neuspješno"] = "Radno mjesto već postoji!";
                    }
                }
            }
            ModelState.Clear();
            var lista = new RadnoMjestoVM();
            lista.tipoviLaptopa = radnoMjestoRepository.DohvatiTipoveLaptopa();
            if (lokacijaID != 0 && lokacijaID!=null)
            {
                TempData["LokacijaID"] = lokacijaID;
                lista.Lokacije = radnoMjestoRepository.DohvatiLokacije((int)lokacijaID);
                lista.LokacijaId = (int)lokacijaID;
            }
            if (lokacijaID == 0 || lokacijaID==null)
            {
                lista.Lokacije = radnoMjestoRepository.DohvatiLokacije();
            }

AplikacijaDijeljenihRadnihMjesta/Views/RadnoMjesto/Create.cshtml
@model AplikacijaDijeljenihRadnihMjesta.Models.ViewModel.RadnoMjestoVM
<link rel="stylesheet" type="text/css" href="~/css/Stranica.css" media="screen" 7 />

<partial name="Upozorenja" view-data="ViewData" />
@{
    ViewData["index"] = "ADMIN";

    var lokacijaID = 0;
    if (TempData["LokacijaID"] != null)
    {
        lokacijaID = (int)@TempData["LokacijaID"];

    }
    else
        lokacijaID = 0;
    var orgJedID = 0;
    if (TempData["OrgJedID"] != null)
    {
        orgJedID = (int)(TempData["OrgJedID"]);
    }
    else
        orgJedID = 0;
    ViewData["ImePrezime"] = TempData["ImePrezime"];
}

<form method="post" asp-action="Create">
    <div class="card p-3 mt-5" style="margin-top:30px!important;     margin: 0 auto;   max-width: 850px !important; justify-content:center!important;">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        @if (lokacijaID != 0)
        {
            <div class="col-1 ">
                <a asp-controller="RadnoMjesto" asp-action="Index" asp-route-LokacijaId="@lokacijaID" asp-route-orgJedID="@orgJedID" ><i class="fas fa-arrow-left" style="justify-content:right; text-align:right; width:min-content; font-size:26px; "></i> </a>
            </div>
        }
        else
        {
            <div class="col-1">
                <a asp-controller="RadnoMjesto" asp-action="Index" asp-route-LokacijaId="@lokacijaID" asp-route-orgJedID="@orgJedID" ><i class="fas fa-arrow-left" style="justify-content:right; text-align:right; width:min-content; font-size:26px; "></i></a>
            </div>
        }
        <div class="form-group row">
            <h2 class="text-info formTitle"> Dodaj novo radno mjesto</h2>
        </div>
        <div class="row">
            <div class="col-10 createRow">
                <div class="form-group row" style="margin-left:15px;">

                    <div class="col-4 colLabel">
                        <label asp-for="@Model.Lokacija">Odaberi lokaciju:</label>
                    </div>
                    <div class="col-8 colInput">

                        <select class="form-select" asp-for="@Model.Lokacija" asp-items="@Model.Lokacije" required>
                        </select>
                    </div>

                    <div class="col-4 colLabel">
                        <label asp-for="Kat"></label>
                    </div>
                    <div class="col-8 colInput">
                        <input asp-for="Kat" class="form-control" />
                        <span asp-validation-for="Kat" class="text-danger"></span>
                    </div>
                    <div class="col-4 colLabel">
                        <label asp-for="Prostorija"></label>
                    </div>
                    <div class="col-8 colInput">
                        <input asp-for="Prostorija" class="form-control" />
                        <span asp-validation-for="Prostorija" class="text-danger"></span>
                    </div>
                    <div class="col-4 colLabel">
                        <label asp-for="BrojRadnogMjesta">Broj radnog mjesta</label>
                    </div>
                    <div class="col-8 colInput">
                        <input asp-for="BrojRadnogMjesta" class="form-control" />
                        <span asp-validation-for="BrojRadnogMjesta" class="text-danger"></span>
                    </div>

                    <div class="col-4 colLabel">
                        <label asp-for="TipLaptopa">Model laptopa</label>
                    </div>
                    <div class="col-8 colInput">
                        <select class="form-select" asp-for="TipLaptopa" asp-items="@Model.tipoviLaptopa" required>
                        </select>
                        <span asp-validation-for="TipLaptopa" class="text-danger"></span>
                    </div>


                </div>
                <div class="form-group row">
                   

                        <div style="justify-content:right;    text-align: right; margin-right:15%">
                            <input type="submit" class="btn btn-success" style="justify-content:center!important; text-align:center!important; width:min-content;" value="Dodaj" />
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

AplikacijaDijeljenihRadnihMjesta/Views/RadnoMjesto/Edit.cshtml
@model AplikacijaDijeljenihRadnihMjesta.Models.ViewModel.RadnoMjestoVM
    <link rel="stylesheet" type="text/css" href="~/css/Stranica.css" media="screen" 7 />
<partial name="Upozorenja" view-data="ViewData" />
@{


    ViewData["index"] = "ADMIN";
    var lokacijaID = 0;
    if (TempData["LokacijaID"] != null)
    {
        lokacijaID =(int)@TempData["LokacijaID"];

    }
    else
        lokacijaID = 0;
    var orgJedID = 0;
    if (TempData["OrgJedID"] != null)
    {
        orgJedID = (int)(TempData["OrgJedID"]);
    }
    else
        orgJedID = 0;
    ViewData["ImePrezime"] = TempData["ImePrezime"];

}
<form method="post" asp-action="Edit">
    <div class="card p-3 mt-5" style="margin-top:30px!important;     margin: 0 auto;   max-width: 850px !important; justify-content:center!important;">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        @if (lokacijaID != 0)
        {
            <a asp-action="Index" asp-route-lokacijaID="@lokacijaID" asp-route-orgJedID="@orgJedID" ><i class="fas fa-arrow-left" style="justify-content:right; text-align:right; width:min-content; font-size:26px; "></i> </a>
        }
        else
        {
            <a asp-action="Index" asp-route-orgJedID="@orgJedID" ><i class="fas fa-arrow-left" style="justify-content:right; text-align:right; width:min-content; font-size:26px; "></i></a>
        }

        <div class="form-group row">
            <h2 class="text-info formTitle"> Uredi informacije o radnom mjestu</h2>
        </div>
        <div class="row">
            <div class="col-10 createRow">
                <div class="form-group row">
                    <div class="col-4 colLabel">
                        <label asp-for="@Model.Lokacija">Odaberi lokaciju:</label>
                    </div>
                    <div class="col-8 colInput">
                        <select class="form-select" asp-for="@Model.Lokacija" asp-items="@Model.Lokacije" required>
                            <option hidden selected="selected" value="@Model.Lokacija">@Model.Lokacija</option>
                        </select>
                    </div>
                    <div class="col-4 colLabel">
                        <label asp-for="Kat"></label>
                    </div>
                    <div class="col-8 colInput">
                        <input asp-for="Kat" class="form-control" />
                    </div>
                    <div class="col-4 colLabel">
                        <label asp-for="Prostorija"></label>
                    </div>
                    <div class="col-8 colInput">
                        <input asp-for="Prostorija" class="form-control" />
                    </div>
                    <div class="col-4 colLabel">
                        <label asp-for="BrojRadnogMjesta">Broj radnog mjesta</label>
                    </div>
                    <div class="col-8 colInput">
                        <input asp-for="BrojRadnogMjesta" class="form-control" />
                    </div>
                    <div class="col-4 colLabel">
                        <label asp-for="TipLaptopa">Model laptopa</label>
                    </div>
                    <div class="col-8 colInput">
                        <select class="form-select" asp-for="TipLaptopa" asp-items="@Model.tipoviLaptopa " required>
                            <option hidden selected="selected" value="@Model.TipLaptopa">@Model.TipLaptopa</option>
                        </select>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-12 row">

                        <div style="justify-content:right;    text-align: right; margin-right:15%">
                            <input type="submit" class="btn btn-success" style="justify-content:center!important; text-align:center!important; width:min-content;" value="Uredi" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

AplikacijaDijeljenihRadnihMjesta/Views/RadnoMjesto/Index.cshtml
@model AplikacijaDijeljenihRadnihMjesta.Models.Paginacija.PaginacijaRadnoMjesto
    <link rel="stylesheet" type="text/css" href="~/css/Stranica.css" media="screen" 7 />
@{
    string lokacijaNaziv = null;
    ViewData["index"] = "ADMIN";
    var lokacijaID = 0;
    if (TempData["LokacijaID"] != null)
    {

        lokacijaID = (int)@TempData["LokacijaID"];

    }
    else
        lokacijaID = 0;
    var orgJedID = 0;
    if (TempData["OrgJedID"] != null)
    {
        orgJedID = (int)(TempData["OrgJedID"]);
    }
    else
        orgJedID = 0;

    ViewData["Controller"] = "RadnoMjesto";
    ViewData["Action"] = "Index";
    ViewData["ImePrezime"] = TempData["ImePrezime"];
    }

<partial name="Upozorenja" view-data="ViewData" />

<div class="card p-3 mt-5" style=" overflow-x: auto;">
    @if ((int)lokacijaID != 0)
    {
        <a asp-controller="Lokacija" asp-action="Index" asp-route-orgJedID="@orgJedID" asp-route-lokacijaID="@lokacijaID"  style=" width: min-content!important;"><i class="fas fa-arrow-left" style="justify-content:right; text-align:right; width:min-content; font-size:26px; "></i> </a>
    }
    else
    {


    }
    <div class="col-12 pt-2 formTitle">
        @if ((int)lokacijaID == 0)
        {
            <h2 class="formTitle" style="text-align:center !important;">Popis radnih mjesta</h2>
        }
        else
        {
            <h2 class="formTitle" style="text-align:center !important;">Popis radnih mjesta na lokaciji </h2>
        }
    </div>
    <form method="post" asp-controller="RadnoMjesto" asp-route-lokacijaID="@lokacijaID" asp-route-tipLaptopaID="@Model.radnoMjestoFilter.TipLaptopaID" asp-action="Index">
        <div class="col-md-12" style="margin-bottom:10px">
            <select class="form-select" style="width:min-content; display:inline-block!important" asp-for="@Model.radnoMjestoFilter.TipLaptopaID" asp-items="@Model.radnoMjestoFilter.ListaTipovaLaptopa">
                <option>Svi modeli</option>
            </select>
            <input type="submit" style=" font-size: 1em !important; margin-left:10px; margin-bottom:4.5px;" class="btn btn-primary" value="Filtriraj" />
            @if ((int)lokacijaID == 0)
            {
                <a style="float:right;text-align:right!important;  color: #2973b2 !important;" asp-controller="RadnoMjesto" asp-route-LokacijaId="@lokacijaID" asp-action="Create">
                    <i class="fas fa-plus" style=" color: #2973b2 !important;"></i>
                </a>
            }

        </div>
    </form>




    @if (Model.radnoMjestoFilter.ListaRadnihMjesta != null && Model.radnoMjestoFilter.ListaRadnihMjesta.Count() > 0)
    {
        <table class="table  tableCss table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Sifra
                    </th>
                    <th>
                        Tip laptopa
                    </th>
                    <th>
                        Adresa
                    </th>
                    <th>
                        Grad
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model.radnoMjestoFilter.ListaRadnihMjesta)
                {
                    <tr>
                        <td id="items" width="30%">@obj.Sifra</td>
                        <td id="items" width="10%">@obj.TipLaptopa</td>
                        <td id="items" width="30%">@obj.Adresa</td>
                        <td id="items" width="10%">@obj.Grad</td>
                        <td class="text-center">
                            <div class="h-25 btn-group" role="group">
                                <a asp-controller="RadnoMjesto" asp-route-orgJedID="@orgJedID" asp-route-lokacijaID="@lokacijaID" asp-route-Sifra="@obj.Sifra" asp-action="Edit" class="btn btn-primary "><i class="fas fa-edit"></i></a>
                                <a data-target="#DeleteModal-@obj.Sifra" data-toggle="modal" class=" btn btn-danger"><i class="fas fa-trash-alt"></i></a>
                                <form method="post" asp-action="Delete" asp-controller="RadnoMjesto"  asp-route-Sifra="@obj.Sifra" asp-route-lokacijaID="@lokacijaID" asp-route-orgJedID="@orgJedID" >
                                    <div class="modal" tabindex="-1" role="dialog" id="DeleteModal-@obj.Sifra">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content" style="margin-top: 30%;">
                                                <div class="modal-header">
                                                    <h5 class="modal-title">Potvrdite brisanje radnog mjesta</h5>
                                                </div>
                                                <div class="modal-body">
                                                    <p>Jeste li sigurni da želite obrisati radno mjesto pod šifrom: @obj.Sifra? </p>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" style="width:min-content;" class="btn btn-primary" data-dismiss="modal">Odustani</button>
                                                    <button type="submit" style="width:min-content;" class="btn btn-danger">Obriši</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>

                            </div>
                        </td>
                    </tr>
                }
            </tbody>

        </table>
        <form style="align-content:center" method="post" asp-controller="Djelatnik" asp-action="Index">
            <partial name="_Pagination" view-data="ViewData" model="Model" />
        </form>
    
    }
    else
    {

        <p>Ne postoji niti jedno radno mjesto na toj lokaciji ili nema radnih mjesta s tim modelom laptopa!</p>

    }


</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }

    
}