AplikacijaDijeljenihRadnihMjesta/Models/OrganizacijskaJedinica.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AplikacijaDijeljenihRadnihMjesta.Models
{
    public class OrganizacijskaJedinica
    {
        public int Id{get; set;}
        public string Naziv{get; set;}
        public IEnumerable<Lokacija> Lokacije{get; set;}
        public IEnumerable<Djelatnik> Djelatnici{get; set;}
        public IEnumerable<LokacijaOrganizacijskaJedinica> LokacijaOrganizacijskaJedinica{get; set;}
    }
}

AplikacijaDijeljenihRadnihMjesta/Controllers/LokacijaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AplikacijaDijeljenihRadnihMjesta.Data;
using AplikacijaDijeljenihRadnihMjesta.Models;
using AplikacijaDijeljenihRadnihMjesta.Models.ViewModel;
using AplikacijaDijeljenihRadnihMjesta.Repository;
using Microsoft.AspNetCore.Http;

namespace AplikacijaDijeljenihRadnihMjesta.Controllers
{
    public class LokacijaController : Controller
    {
        private LokacijaRepository lokacijaRepository;
        const string SessionOrgJedinica = "_OrgJedinicaID";
        const string SessionOrgJedinicaNaziv = "_OrgJedinicaNaziv";
        const string SessionStaraOrgJedinicaID = "_StaraOrgJedinicaID";


        public LokacijaController(AppDbContext db)
        {
            this.lokacijaRepository = new LokacijaRepository(db);
        }
        [HttpGet]
        public IActionResult Index(int? orgJedID, string nazivOrgJed)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            if (orgJedID != 0 && orgJedID != null)
            {
                HttpContext.Session.SetInt32(SessionOrgJedinica, (int)orgJedID);
                TempData["OrgJedID"] = orgJedID;
                TempData["NazivOrgJed"] = lokacijaRepository.DohvatiNazivOrgJedinice((int)orgJedID);
                HttpContext.Session.SetString(SessionOrgJedinicaNaziv, lokacijaRepository.DohvatiNazivOrgJedinice((int)orgJedID));
                return View(lokacijaRepository.DohvatiListuLokacija((int)orgJedID));
            }
            else
            {
                TempData["OrgJedID"] = null;
                var lok = new LokacijaFilter();
                lok = lokacijaRepository.DohvatiListuLokacija();
                foreach (var org in lok.ListaLokacija)
                {
                    var lista= lokacijaRepository.DohvatiOrgJedNaLokaciji(org.Id);
                    foreach (var l in lista)
                    {
                        org.ListaOrganizacijskihJedinica += "-";
                        org.ListaOrganizacijskihJedinica +=( l + "\r\n");
                        //org.ListaOrganizacijskihJedinica += System.Environment.NewLine;
                    }
                    org.ListaOrganizacijskihJedinica = string.Join(", ",lista);

                    //org.ListaOrganizacijskihJedinica.Remove(org.ListaOrganizacijskihJedinica.Length - 2);
                }
                return View(lok);
            }
                
        }
        [HttpPost]
        public IActionResult Index(int? orgJedID, int? GradID)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            if (orgJedID != 0 && GradID == null)
            {
                var nazivOrgJed = HttpContext.Session.GetString(SessionOrgJedinicaNaziv);
                HttpContext.Session.SetInt32(SessionOrgJedinica, (int)orgJedID);
                TempData["OrgJedID"] = orgJedID;
                TempData["NazivOrgJed"] = nazivOrgJed;
                return View(lokacijaRepository.DohvatiListuLokacija((int)orgJedID));
            }
            else if (orgJedID == 0 && GradID != null )
            {
                return View(lokacijaRepository.DohvatiListuLokacijaFiltriranuPoGradu((int)GradID));
            }
            else if (orgJedID != 0 && GradID != null )
            {
                var nazivOrgJed=HttpContext.Session.GetString(SessionOrgJedinicaNaziv);
                TempData["OrgJedID"] = orgJedID;
                TempData["NazivOrgJed"] = nazivOrgJed;
                return View(lokacijaRepository.DohvatiListuLokacija((int)orgJedID, (int)GradID));
            }
            else
                return View(lokacijaRepository.DohvatiListuLokacija());
        }

        //GET-CREATE
        public IActionResult Create(int? orgJedID)
        {
            TempData["OrgJedID"] = HttpContext.Session.GetInt32(SessionOrgJedinica);
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            var lista = new LokacijaVM();
            lokacijaRepository.DohvatiGradove(lista);
            if (orgJedID != 0)
            {
                lokacijaRepository.DohvatiOrgJedinice(lista,(int)orgJedID);
            }
            else
            {
                lokacijaRepository.DohvatiOrgJedinice(lista);
            }
            return View(lista);
        }

        //POST-CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(LokacijaVM lokacija)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            if (lokacijaRepository.DodajNovuLokaciju(lokacija))
            {
                TempData["OrgJedID"] = HttpContext.Session.GetInt32(SessionOrgJedinica);
                TempData["Uspješno"] = "Uspješno dodana nova lokacija!";
            }
            else
            {
                TempData["Neuspješno"] = "Lokacija već postoji!";
            }
            ModelState.Clear();
            var lista = new LokacijaVM();
            lista.Gradovi = lokacijaRepository.DohvatiGradove();
            if (TempData["OrgJedID"] != null)
            {
                lokacijaRepository.DohvatiOrgJedinice(lista, (int)TempData["OrgJedID"]);
            }
            else
                lokacijaRepository.DohvatiOrgJedinice(lista);
            return View(lista);
        }

        //GET-DELETE
        public IActionResult Delete(int? id, int? orgJedID)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            TempData["OrgJedID"] = HttpContext.Session.GetInt32(SessionOrgJedinica);
            var nazivOrgJed = HttpContext.Session.GetString(SessionOrgJedinicaNaziv);
            if (ModelState.IsValid)
            {
                if (orgJedID != null)
                {
                    if (lokacijaRepository.IzbrisiLokacijuUnutarOrgJedinice((int)id, (int)orgJedID))
                    {
                        TempData["Uspješno"] = $"Uspješno izbrisana lokacija iz organizacijske jedinice: {nazivOrgJed}!";
                    }
                    else
                    {
                        TempData["Neuspješno"] = $"Neuspješno brisanje lokacije iz organizacijske jedinice:{nazivOrgJed} !";
                    }
                }
                else
                {
                    if (lokacijaRepository.IzbrisiLokaciju((int)id))
                    {
                        TempData["Uspješno"] = "Uspješno izbrisana lokacija!";
                    }
                    else
                    {
                        TempData["Neuspješno"] = "Neuspješno brisanje lokacije, pogledajte postoje li radna mjesta na toj lokaciji prije brisanja !";
                    }
                }
            }
            ModelState.Clear();
            if (orgJedID != 0)
            {
                return RedirectToAction("Index", new
                {
                    orgJedID = orgJedID
                });
            }
            return RedirectToAction("Index");
        }

        //public IActionResult DohvatiOrgJed(int? id, int? orgJedID)
        //{
        //    TempData["OrgJedID"] = HttpContext.Session.GetInt32(SessionOrgJedinica);
        //    var nazivOrgJed = HttpContext.Session.GetString(SessionOrgJedinicaNaziv);

        //    var lista=lokacijaRepository.DohvatiOrgJedNaLokaciji((int)id);
        //    var orgJedinice = new LokacijaFilter();
        //    orgJedinice.ListaOrganizacijskihJedinica = lista;
        //    if (orgJedID != 0)
        //    {
        //        return RedirectToAction("Index", new
        //        {
        //            orgJedID = orgJedID
        //        });
        //    }
        //    return RedirectToAction("Index");
        //}

        //GET-EDIT
        public IActionResult Edit(int? id, int? orgJedID)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            var lokacija = lokacijaRepository.DohvatiLokacijuPoId(id); //lokacija iz baze
            var gradovi = lokacijaRepository.DohvatiGradove();
            if (id != null)
            {
                if (orgJedID != 0 && orgJedID!=null)
                {
                    HttpContext.Session.SetInt32(SessionStaraOrgJedinicaID, (int)orgJedID);
                    var OrgJed = lokacijaRepository.DohvatiOrgJedinice((int)orgJedID);
                    TempData["OrgJedID"] = HttpContext.Session.GetInt32(SessionOrgJedinica);
                    var lokacijaModel = new LokacijaVM{ Id = lokacija.Id, Adresa = lokacija.Adresa, Gradovi = gradovi, Grad = lokacijaRepository.DohvatiNazivGrada(lokacija), OrgJedinica = lokacijaRepository.DohvatiNazivOrgJedinice((int)orgJedID), OrgJedinice = OrgJed };
                    lokacijaModel = lokacijaRepository.DohvatiPripadajuceOrgJedinice(lokacijaModel);
                    return View(lokacijaModel);
                }
                else
                {
                    var lokacijaModel = new LokacijaVM{ Id = lokacija.Id, Adresa = lokacija.Adresa, Gradovi = gradovi, Grad = lokacijaRepository.DohvatiNazivGrada(lokacija), OrgJedinica = lokacijaRepository.DohvatiNazivOrgJedinicePoID(lokacija.Id), OrgJedinice = lokacijaRepository.DohvatiOrgJedinice() };
                    lokacijaModel = lokacijaRepository.DohvatiPripadajuceOrgJedinice(lokacijaModel);
                    return View(lokacijaModel);
                    
                }
            }
            return NotFound();
        }



        //POST-EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(LokacijaVM lokacija)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            TempData["OrgJedID"] = HttpContext.Session.GetInt32(SessionOrgJedinica);
            var orgJedID = TempData["OrgJedID"];
            if (lokacijaRepository.EditLokacija(lokacija))

AplikacijaDijeljenihRadnihMjesta/Controllers/OrganizacijskaJedinicaController.cs
using AplikacijaDijeljenihRadnihMjesta.Data;
using AplikacijaDijeljenihRadnihMjesta.Models.ViewModel;
using AplikacijaDijeljenihRadnihMjesta.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AplikacijaDijeljenihRadnihMjesta.Controllers
{
    public class OrganizacijskaJedinicaController : Controller
    {
        private OrgJedinicaRepository orgJedinicaRepository;
        
        const string SessionOrgJed= "_OrgJedID";

        public OrganizacijskaJedinicaController(AppDbContext db)
        {
            this.orgJedinicaRepository = new OrgJedinicaRepository(db);
        }
        [HttpGet]
        public IActionResult Index()
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            //try
            //{

            //    return View(orgJedinicaRepository.DohvatiPopisOrgJedinica());
            //}
            //catch (Exception ex)
            //{
            //    Console.Write("Error info:" + ex.Message);
            //    return View()
            //}
            return View(orgJedinicaRepository.DohvatiPopisOrgJedinica());
        }

        //GET-CREATE
        public IActionResult Create()
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            return View();
        }

        //POST-CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(OrgJedinicaVM orgJedinica)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            if (orgJedinicaRepository.DodajNovuOrgJedinicu(orgJedinica))
            {
                TempData["Uspješno"] = "Uspješno dodana nova organizacijska jedinica!";
            }
            else
            {
                TempData["Neuspješno"] = "Organizacijska jedinica već postoji!";
            }
            ModelState.Clear();
            return View();
        }

        //GET-EDIT
        public IActionResult Edit(int id)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            if (id != 0)
            {
                var orgJedinica = orgJedinicaRepository.DohvatiOrgJedinicuPoID(id);
                HttpContext.Session.SetInt32(SessionOrgJed, orgJedinica.Id);
                return View(new OrgJedinicaVM { Naziv = orgJedinica.Naziv });
            }
            return NotFound();
        }

        //POST-EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(OrgJedinicaVM orgJed)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            if (ModelState.IsValid)
            {
                var orgJedID = HttpContext.Session.GetInt32(SessionOrgJed);
                if (orgJedinicaRepository.EditOrgJedinicu(orgJed, (int)orgJedID))
                {
                    TempData["Uspješno"] = "Uspješno promijenjen naziv organizacijske jedinice!";
                }
                else
                {
                    TempData["Neuspješno"] = "Neuspješna promjena naziva organizacijske jedinice! Pogledajte postoji li organizacijska jedinica s tim nazivom.";
                }
            }
            ModelState.Clear();
            return View(orgJed);
        }

        //GET-DELETE
        public IActionResult Delete(int id)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            if (ModelState.IsValid)
            {
                if (orgJedinicaRepository.IzbrisiOrgJedinicu(id))
                {
                    TempData["Uspješno"] = "Uspješno izbrisana organizacijska jedinica!";
                }
                else
                {
                    TempData["Neuspješno"] = "Neuspješno brisanje organizacijske jedinice jer u njoj postoje zaposlenici!";
                }
            }
            ModelState.Clear();
            return RedirectToAction("Index");
        }

        //GET-DODAJLOKACIJE
        public IActionResult DodajLokacije(int orgJedID)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            TempData["OrgJedID"] = orgJedID;
            var lista = orgJedinicaRepository.DohvatiListuLokacija(orgJedID);
            HttpContext.Session.SetInt32(SessionOrgJed, orgJedID);
            lista.OrgJedID = orgJedID;
            return View(lista);
        }

        //POST-DODAJLOKACIJE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DodajLokacije(LokacijaORgJedinicaVM orgJedinica)
        {
            TempData["ImePrezime"] = HttpContext.Session.GetString("ImePrezime");
            var orgJedID = HttpContext.Session.GetInt32(SessionOrgJed);
            TempData["OrgJedID"] = orgJedID;
            if (orgJedinicaRepository.DodajNovuLokacijuUOrgJedinicu(orgJedinica, (int)orgJedID))
            {
                TempData["Uspješno"] = "Uspješno dodana nova lokacija u organizacijsku jedinicu!";
            }
            else
            {
                TempData["Neuspješno"] = "Lokacija je već u sklopu organizacijske jedinice!";
            }
            ModelState.Clear();
            var lista = orgJedinicaRepository.DohvatiListuLokacija((int)orgJedID);
            return View(lista);
        }

       

    }
}

AplikacijaDijeljenihRadnihMjesta/Views/OrganizacijskaJedinica/Create.cshtml
@model AplikacijaDijeljenihRadnihMjesta.Models.ViewModel.OrgJedinicaVM
@{
    ViewData["index"] = "ADMIN";
    ViewData["ImePrezime"] = TempData["ImePrezime"];
}
<partial name="Upozorenja" view-data="ViewData" />
<link rel="stylesheet" type="text/css" href="~/css/Stranica.css" media="screen" 7 />
<form method="post" asp-action="Create">

    <div class="card p-3 mt-5" style="margin-top:30px!important;     margin: 0 auto;   max-width: 850px !important; justify-content:center!important;">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <a asp-controller="OrganizacijskaJedinica" asp-action="Index"><i class="fas fa-arrow-left" style="justify-content:right; text-align:right; width:min-content; font-size:26px; "></i></a>
        <div class="form-group row">
            <h2 class="text-info formTitle"> Dodaj novu organizacijsku jedinicu</h2>
        </div>
        <div class="row">
            <div class="col-10 createRow">
                <div class="form-group row">
                    <div class="col-4 colLabel">
                        <label asp-for="Naziv"></label>
                    </div>
                    <div class="col-8 colInput">
                        <input asp-for="Naziv" class="form-control" required />
                        <span asp-validation-for="Naziv" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">


                    <div style="justify-content:right;    text-align: right; margin-right:15%">
                        <input type="submit" class="btn btn-success" style="justify-content:center!important; text-align:center!important; width:min-content;" value=" Dodaj" />
                    </div>





                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

AplikacijaDijeljenihRadnihMjesta/Views/OrganizacijskaJedinica/DodajLokacije.cshtml
@model AplikacijaDijeljenihRadnihMjesta.Models.ViewModel.LokacijaORgJedinicaVM
    <link rel="stylesheet" type="text/css" href="~/css/Stranica.css" media="screen" 7 />
    <partial name="Upozorenja" view-data="ViewData" />
    @{
        ViewData["index"] = "ADMIN";
        var orgJedID = 0;
        if (TempData["OrgJedID"] != null)
        {
            orgJedID = (int)(TempData["OrgJedID"]);
        }
        else
            orgJedID = 0;
        ViewData["ImePrezime"] = TempData["ImePrezime"];
    }
<form method="post" asp-action="DodajLokacije">
   
    <div class="card p-3 mt-5" style="margin-top:30px!important;     margin: 0 auto;   max-width: 850px !important; justify-content:center!important;">
        @if ((int)orgJedID != 0)
        {
            <a asp-controller="Lokacija" asp-action="Index" asp-route-orgJedID="@orgJedID"><i class="fas fa-arrow-left" style="justify-content:right; text-align:right; width:min-content; font-size:26px; "></i></a>
        }
        else
        {
            <a asp-action="Index"><i class="fas fa-arrow-left" style="justify-content:right; text-align:right; width:min-content; font-size:26px; "></i> </a>
        }
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">

            <h2 class="text-info formTitle"> Dodaj lokacije u organizacijsku jedinicu</h2>

        </div>
        <div class="row">
            <div class="col-10 createRow">
                <div class="form-group row">
                    <div class="col-4 colLabel">
                        <label asp-for="Adresa">Adresa</label>
                    </div>
                    <div class="col-8 colInput">
                        <select class="form-select" asp-for="Adresa" asp-items="@Model.Adrese" required>
                        </select>
                        <span asp-validation-for="Adresa" class="text-danger"></span>
                    </div>




                </div>
                <div class="form-group row">

                    <div class="col-12 row">
                        <div style="justify-content:right;    text-align: right; margin-right:15%">
                            <input type="submit" class="btn btn-success" style="justify-content:center!important; text-align:center!important; width:min-content;" value="Dodaj" />
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

</form>

    @section Scripts{
        @{
            <partial name="_ValidationScriptsPartial" />
        }
    }

AplikacijaDijeljenihRadnihMjesta/Views/OrganizacijskaJedinica/Edit.cshtml
@model AplikacijaDijeljenihRadnihMjesta.Models.ViewModel.OrgJedinicaVM
    <link rel="stylesheet" type="text/css" href="~/css/Stranica.css" media="screen" 7 />
<partial name="Upozorenja" view-data="ViewData" />
@{
    var orgJedID = 0;
    ViewData["index"] = "ADMIN";
    if (TempData["OrgJedID"] != null)
    {
        orgJedID = (int)(TempData["OrgJedID"]);
    }
    else
        orgJedID = 0;
    ViewData["ImePrezime"] = TempData["ImePrezime"];

}
<form method="post" asp-action="Edit">
    <input asp-for="Id" hidden />
    <div class="card p-3 mt-5" style="margin-top:30px!important;     margin: 0 auto;   max-width: 850px !important; justify-content:center!important;">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <a asp-action="Index"><i class="fas fa-arrow-left" style="justify-content:right; text-align:right; width:min-content; font-size:26px; "></i> </a>
        <div class="form-group row">
            <h2 class="text-info formTitle"> Uredi informacije o organizacijskoj jedinici</h2>
        </div>
        <div class="row">
            <div class="col-10 createRow">
                <div class="form-group row">
                    <div class="col-4 colLabel">
                        <label asp-for="Naziv"></label>
                    </div>
                    <div class="col-8 colInput">
                        <input asp-for="Naziv" class="form-control" required />
                    </div>

                </div>


            </div>
            <div class="form-group row">
                <div class="col-12 row"><div style="justify-content:right;    text-align: right; margin-right:15%">
                        <input type="submit" class="btn btn-success" style="justify-content:center!important; text-align:center!important; width:min-content;" value="Uredi" />
                    </div>
                </div>

            </div>
        </div>

    </div>


</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

AplikacijaDijeljenihRadnihMjesta/Views/OrganizacijskaJedinica/Index.cshtml
@model IEnumerable<AplikacijaDijeljenihRadnihMjesta.Models.ViewModel.OrgJedinicaVM>

<link rel="stylesheet" type="text/css" href="~/css/Stranica.css" media="screen" 7 />
<partial name="Upozorenja" view-data="ViewData" />
@{
    ViewData["index"] = "ADMIN";
    ViewData["ImePrezime"] = TempData["ImePrezime"];
}

<div class="card p-3 mt-5" style=" overflow-x: auto;">
    <div class="col-12 pt-2 formTitle">
        <h2 class="formTitle" style="text-align:center !important;">Popis organizacijskih jedinica</h2>
    </div>
    <div style="float:right;">
        <a style="float:right; text-align:right!important " asp-controller="OrganizacijskaJedinica" asp-action="Create">
            <i class="fas fa-plus" style=" color: #2973b2 !important; margin-bottom:10px;"></i>
        </a>
    </div>



    @if (Model != null && Model.Count() > 0)
    {
        <table class="table tableCss table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Naziv
                    </th>
                    <th>
                        Djelatnici
                    </th>
                    <th>
                        Informacije o djelatnicima
                    </th>
                    <th>
                        Lokacije
                    </th>
                    <th>
                        Informacije o lokacijama
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td id="items" width="20%">@obj.Naziv</td>
                        <td id="items" width="10%">@obj.BrojDjelatnika </td>
                        <td class="text-center">
                            <div class="w-25 btn-group" role="group">
                                <a asp-controller="Djelatnik" asp-route-orgJedID="@obj.Id" asp-action="Index" class="btn btn-info "><i class="fas fa-info"></i></a>

                            </div>
                        </td>
                        <td id="items" width="10%">@obj.BrojLokacija </td>
                        <td class="text-center">
                            <div class="w-25 btn-group" role="group">
                                <a asp-controller="Lokacija" asp-route-orgJedID="@obj.Id" asp-route-nazivOrgJed="@obj.Naziv" asp-action="Index" class="btn btn-info "><i class="fas fa-info"></i></a>

                            </div>
                        </td>
                        <td class="text-center">
                            <div class=" btn-group" style="width:min-content!important;" role="group">
                                <a asp-controller="OrganizacijskaJedinica" asp-route-Id="@obj.Id" asp-action="Edit" class="btn btn-primary "><i class="fas fa-edit"></i></a>

                                <a data-target="#DeleteModal-@obj.Id" data-toggle="modal" class=" btn btn-danger"><i class="fas fa-trash-alt"></i></a>
                                <form method="post" asp-action="Delete" asp-controller="OrganizacijskaJedinica" asp-route-Id="@obj.Id">
                                    <div class="modal" tabindex="-1" role="dialog" id="DeleteModal-@obj.Id">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content" style="margin-top: 30%;">
                                                <div class="modal-header">
                                                    <h5 class="modal-title">Potvrdite brisanje organizacijske jedinice</h5>
                                                </div>
                                                <div class="modal-body">
                                                    <p>Jeste li sigurni da želite obrisati organizacijsku jedinicu @obj.Naziv? </p>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" style="width:min-content;" class="btn btn-primary" data-dismiss="modal">Odustani</button>
                                                    <button type="submit" style="width:min-content;" class="btn btn-danger">Obriši</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    }
    else
    {
        <p>Ne postoji niti jedna organizacijska jedinica!</p>
    }
</div>

    @section Scripts{
        @{
            <partial name="_ValidationScriptsPartial" />
        }

    }